import { useState } from 'react';
import { Building2, CheckCircle2, Clock3, Plus, ShieldAlert } from 'lucide-react';
import { useChangeTenantStatusMutation, useCreateTenantMutation, useDecidePaymentMutation, usePlatformOverviewQuery, usePlatformTenantsQuery } from '../store/api.js';
import PageHeader from '../components/PageHeader.jsx';
import Modal from '../components/Modal.jsx';

export default function Platform() {
  const { data: overview } = usePlatformOverviewQuery(); const { data: tenants } = usePlatformTenantsQuery();
  const [decide, decision] = useDecidePaymentMutation(); const [changeStatus] = useChangeTenantStatusMutation(); const [createTenant, createState] = useCreateTenantMutation();
  const [open, setOpen] = useState(false); const [message, setMessage] = useState(''); const [form, setForm] = useState({ businessName: '', slug: '', email: '', phone: '', adminName: '', username: '', password: '' });
  const metrics = overview?.data?.metrics || {};
  const paymentDecision = async (id, choice) => { const reason = window.prompt(`Reason for ${choice.toLowerCase()}:`, choice === 'APPROVED' ? 'Payment verified' : 'Payment evidence requires review'); if (reason) await decide({ id, decision: choice, reason }); };
  const suspend = async (tenant) => { const next = tenant.status === 'SUSPENDED' ? 'ACTIVE' : 'SUSPENDED'; const reason = window.prompt(`Reason for ${next.toLowerCase()}:`); if (reason) await changeStatus({ id: tenant._id, status: next, reason }); };
  const createBusiness = async (e) => { e.preventDefault(); setMessage(''); try { await createTenant(form).unwrap(); setOpen(false); } catch (err) { setMessage(err.data?.error?.message || 'Unable to create business'); } };
  return <><PageHeader title="Platform Control" subtitle="Manage businesses, payments, subscriptions and access" action={<button className="primary" onClick={() => setOpen(true)}><Plus /> New business</button>} /><section className="platform-metrics"><article><Building2 /><div><span>All businesses</span><b>{metrics.tenants || 0}</b></div></article><article><CheckCircle2 /><div><span>Active</span><b>{metrics.active || 0}</b></div></article><article><Clock3 /><div><span>Pending payments</span><b>{metrics.pendingPayments || 0}</b></div></article><article><ShieldAlert /><div><span>Suspended</span><b>{metrics.suspended || 0}</b></div></article></section>
    <section className="panel"><h2>Payment review queue</h2><div className="table-wrap"><table><thead><tr><th>Business</th><th>Reference</th><th>Amount</th><th>Method</th><th>Status</th><th>Actions</th></tr></thead><tbody>{overview?.data?.recentPayments?.map((p) => <tr key={p._id}><td>{p.tenantId?.name || 'Unknown'}</td><td>{p.reference}</td><td>${(p.amountMinor / 100).toFixed(2)}</td><td>{p.method}</td><td><span className={`status ${p.status === 'APPROVED' ? 'paid' : p.status === 'PENDING_REVIEW' ? 'partial' : 'unpaid'}`}>{p.status.replaceAll('_', ' ')}</span></td><td className="actions">{p.status === 'PENDING_REVIEW' && <><button className="small approve" disabled={decision.isLoading} onClick={() => paymentDecision(p._id, 'APPROVED')}>Approve</button><button className="small reject" onClick={() => paymentDecision(p._id, 'REJECTED')}>Reject</button></>}</td></tr>)}</tbody></table></div></section>
    <section className="panel"><h2>Business accounts</h2><div className="table-wrap"><table><thead><tr><th>Business</th><th>Email</th><th>Tenant status</th><th>Subscription</th><th>Expires</th><th>Control</th></tr></thead><tbody>{tenants?.data?.map((tenant) => <tr key={tenant._id}><td><b>{tenant.name}</b><small className="block">{tenant.slug}</small></td><td>{tenant.email}</td><td><span className={`status ${tenant.status === 'ACTIVE' ? 'paid' : 'unpaid'}`}>{tenant.status.replaceAll('_', ' ')}</span></td><td>{tenant.subscription?.status?.replaceAll('_', ' ') || 'NONE'}</td><td>{tenant.subscription?.expiresAt ? new Date(tenant.subscription.expiresAt).toLocaleDateString() : '—'}</td><td><button className={`small ${tenant.status === 'SUSPENDED' ? 'approve' : 'reject'}`} onClick={() => suspend(tenant)}>{tenant.status === 'SUSPENDED' ? 'Restore' : 'Suspend'}</button></td></tr>)}</tbody></table></div></section>
    {open && <Modal title="Create business account" onClose={() => setOpen(false)}><form className="form-grid" onSubmit={createBusiness}><label>Business name<input value={form.businessName} onChange={(e) => setForm({ ...form, businessName: e.target.value, slug: e.target.value.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '') })} required /></label><label>Workspace slug<input value={form.slug} onChange={(e) => setForm({ ...form, slug: e.target.value })} required /></label><label>Business email<input type="email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} required /></label><label>Phone<input value={form.phone} onChange={(e) => setForm({ ...form, phone: e.target.value })} /></label><label>Admin name<input value={form.adminName} onChange={(e) => setForm({ ...form, adminName: e.target.value })} required /></label><label>Admin username<input value={form.username} onChange={(e) => setForm({ ...form, username: e.target.value })} required /></label><label className="full">Temporary password<input type="password" minLength="8" value={form.password} onChange={(e) => setForm({ ...form, password: e.target.value })} required /></label>{message && <div className="form-error full">{message}</div>}<div className="modal-actions full"><button type="button" className="secondary" onClick={() => setOpen(false)}>Cancel</button><button className="primary" disabled={createState.isLoading}>{createState.isLoading ? 'Creating…' : 'Create business'}</button></div></form></Modal>}
  </>;
}
