import express from 'express';
import cors from 'cors';
import helmet from 'helmet';
import cookieParser from 'cookie-parser';
import morgan from 'morgan';
import rateLimit from 'express-rate-limit';
import { env } from './config/env.js';
import authRoutes from './routes/auth.routes.js';
import dashboardRoutes from './routes/dashboard.routes.js';
import salesRoutes from './routes/sales.routes.js';
import usersRoutes from './routes/users.routes.js';
import billingRoutes from './routes/billing.routes.js';
import platformRoutes from './routes/platform.routes.js';
import purchaseRoutes from './routes/purchases.routes.js';
import inventoryRoutes from './routes/inventory.routes.js';
import paymentsRoutes from './routes/payments.routes.js';
import { productRoutes, customerRoutes, vendorRoutes, expenseRoutes } from './routes/resources.routes.js';
import { authenticate, requireTenant } from './middleware/auth.js';
import { requireActiveSubscription } from './middleware/subscription.js';
import { errorHandler, notFound } from './middleware/error.js';

const app = express();
app.set('trust proxy', 1);
app.use(helmet());
app.use(cors({ origin: env.CLIENT_URL, credentials: true }));
app.use(express.json({ limit: '1mb' }));
app.use(cookieParser());
app.use(morgan(env.NODE_ENV === 'production' ? 'combined' : 'dev'));
app.use('/api/v1/auth', rateLimit({ windowMs: 15 * 60 * 1000, limit: 100, standardHeaders: true, legacyHeaders: false }), authRoutes);
app.get('/api/v1/health', (_req, res) => res.json({ success: true, service: 'maamulpro-api', timestamp: new Date().toISOString() }));
app.use('/api/v1/platform', authenticate, platformRoutes);

const tenantRouter = express.Router();
tenantRouter.use(authenticate, requireTenant);
tenantRouter.use('/billing', billingRoutes);
tenantRouter.use(requireActiveSubscription);
tenantRouter.use('/dashboard', dashboardRoutes);
tenantRouter.use('/inventory', inventoryRoutes);
tenantRouter.use('/products', productRoutes);
tenantRouter.use('/customers', customerRoutes);
tenantRouter.use('/vendors', vendorRoutes);
tenantRouter.use('/expenses', expenseRoutes);
tenantRouter.use('/sales', salesRoutes);
tenantRouter.use('/purchases', purchaseRoutes);
tenantRouter.use('/payments', paymentsRoutes);
tenantRouter.use('/users', usersRoutes);
app.use('/api/v1', tenantRouter);

app.use(notFound);
app.use(errorHandler);
export default app;
